### ISSUE TITLE
Cassandra startup not waiting for network.target when configured with systemd

### ISSUE THREAD

**Issue by tkazmierczak-tt** [locp/ansible-role-cassandra#66]
**Describe the bug**
When configured using the provided systemd Fedora templates cassandra service starts before network is available. This fails with a system log like:
```
ERROR [main] 2019-09-26 09:38:52,542 CassandraDaemon.java:749 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Unable to bind to address /10.77.17.103:7000. Set listen_address in cassandra.yaml to an interface you can bind to, e.g., your private IP address on EC2
        at org.apache.cassandra.net.MessagingService.getServerSockets(MessagingService.java:739) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:681) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.net.MessagingService.listen(MessagingService.java:665) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:796) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:683) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:632) ~[apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:388) [apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:620) [apache-cassandra-3.11.4.jar:3.11.4]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:732) [apache-cassandra-3.11.4.jar:3.11.4]
```
Luckily after 60s when the network is fully initialized the service gets restarted due to the systemd Restart=always and RestartSec=60 parameters, so it's not so annoying.
**To Reproduce**
Steps to reproduce the behaviour:
I tested it on a CentOS 7 host with key role parameters:
  * cassandra_systemd_enabled: True
  * listen_address: ansible_eth0.ipv4.address
  * cassandra_systemd_template: "systemd/system/Fedora/30/cassandra.service.j2"

**Expected behaviour**
The cassandra service should wait for the network target and start after it's fully initialized. This can be achieved by adding
```
After=network.target
```
to the systemd unit file.
**Versions (please complete the following information):**
- Ansible version: 2.8.0
- Role version: 1.0.2
- Python version: 2.7.15

**Comment by dallinb** [comment]
Thank you for the feedback and the excellent description of the problem.  Working on the fix now.

**Comment by dallinb** [comment]
I have made the change in a branch that can be viewed at https://github.com/locp/ansible-role-cassandra/blob/bugfix/wait_for_network.target/templates/systemd/system/Fedora/30/cassandra.service.j2 .  However would you prefer me to also copy that to a template target called `systemd/system/CentOS/7/cassandra.service.j2` as well?  In the testing we do at https://travis-ci.org/locp/ansible-role-cassandra we only test against systemd for Fedora at the moment.  This may change when CentOS 8 is released as a Docker image and we start testing against that.

**Comment by dallinb** [comment]
I have gone ahead and created the template for you.  I have also changed the test suite to specify that CentOS 7 will be tested with systemd.  Will get this bundled into a release as soon as possible (you will be able to check the version number when I set the "milestone" of this issue).  Please note that this means that you will also not have to specify the `cassandra_systemd_template` parameter with this new release.

**Comment by tkazmierczak-tt** [comment]
Yes, it's great that you provided the systemd unit file for CentOS 7. This way users won't have to set cassandra_systemd_template: "systemd/system/Fedora/30/cassandra.service.j2" on CentOS 7 platform. The moment I checked it there weren't aby differences between Fedora 29 and Fedora 30 systemd unit files, maybe there is no need to distinguish the unit file template between different platforms at all.

**Comment by dallinb** [comment]
Thank you for the response.  I agree that at the moment all the templates for systemd are identical.  I guess I'm torn between your valid suggestion or future proofing when there is a distribution that does have a difference (a tricky one).
