### ISSUE TITLE
Previously Working Molecule Tests Now Failing

### ISSUE THREAD

**Issue by dallinb** [locp/ansible-role-cassandra#89]
**Describe the bug**
Testing on TravisCI worked fine about a month ago.  Now Fedora builds are failing (see https://travis-ci.com/github/locp/ansible-role-cassandra/jobs/352385575).

**To Reproduce**
Attempt the molecule tests against Fedora.  Happens locally as well saying that the container can't find /usr/sbin/init

**Expected behaviour**
The container should start successfully and run the tests.

**Screenshots**
```JSON
{
  "ansible_job_id": "182289384476.3843",
  "ansible_loop_var": "item",
  "attempts": 1,
  "changed": false,
  "finished": 1,
  "item": {
    "ansible_job_id": "182289384476.3843",
    "ansible_loop_var": "item",
    "changed": true,
    "failed": false,
    "finished": 0,
    "item": {
      "command": "/usr/sbin/init",
      "groups": [
        "cassandra",
        "clustered",
        "fedora31"
      ],
      "image": "fedora:31",
      "name": "node0",
      "privileged": true
    },
    "results_file": "/Users/ben.dalling/.ansible_async/182289384476.3843",
    "started": 1
  },
  "msg": "Error starting container 68d4c338b9441911938f0c24527c1908e8b68192b9da2806bd92cade30a6511b: 400 Client Error: Bad Request (\"OCI runtime create failed: container_linux.go:349: starting container process caused \"exec: \\\"/usr/sbin/init\\\": stat /usr/sbin/init: no such file or directory\": unknown\")"
}
```

**Versions (please complete the following information):**
Happens on Fedora 30, 31 and 32.

**Additional context**
This has worked fine about a month and there have been no changes to the code.

**Comment by dallinb** [comment]
While the problem with the Fedora builds has now been resolved, we can't merge the PR as the tests are now failing for CentOS.  In this case, this is because TravisCI is killing the tests because the build on CentOS is taking over 50 minutes.  I have already attempted removing the `check` stage in the secondary and tertiary scenarios.  While this reduced sometime, it's still not enough.  Looking at how else we can speed this up, stuff to look at includes:

- Seeing how much parallelisation we can achieve.
- Can we merge the secondary and tertiary scenarios.
- Refactor the Ansible code.  Following the progress on travis, even skipped tasks are taking a long time.
- Optimise the verification tests.

At the moment on this branch, running `time molecule test` from cold (containers not created) is taking 271.15s.

**Comment by dallinb** [comment]
Running `molecule test --parallel` takes 254.95s.

**Comment by dallinb** [comment]
Reverted that as `ERROR: Combining "--parallel" and "--destroy=never" is not supported`

**Comment by dallinb** [comment]
I have now combined the scenarios for adding nodes 2 and 3 to the combined cluster.  This very nearly worked for CentOS with the job being timed out just after the final verification steps were completed!!!!  However, now failing on Debian.  I vaguely remember this happening in testing (on Debian) with some clash when more than one node was joining the cluster.  Can't recreate right now though.

Fundamentally this issue is being caused by CentOS builds taking far too long.  The last successful build on CentOS for 1.4.0 of this module (i.e. last time the code was changed) was 37 minutes.  So trying to track down why this has become an issue now?  Obviously we have had a change in Fedora with systemd now having to be installed specifically (when we didn't before), but why CentOS is taking over 50 minutes when it used to take 37 and now after changing the test suite, Fedora finishes in under 23 minutes.

**Comment by dallinb** [comment]
This is like Wack-a-Mole!!!! CentOS built successfully (in 46 minutes).  Fedora timed out!!!!! Ubuntu and Debian failed with presumably something similar to:

```
INFO  [main] 2020-07-31 07:23:23,229 StorageService.java:1478 - JOINING: calculation complete, ready to bootstrap
ERROR [main] 2020-07-31 07:23:23,244 CassandraDaemon.java:775 - Exception encountered during startup
java.lang.UnsupportedOperationException: Other bootstrapping/leaving/moving nodes detected, cannot bootstrap while cassandra.consistent.rangemovement is true. Nodes detected, bootstrapping: /172.17.0.4; leaving: ; moving: ;
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:963) ~[apache-cassandra-3.11.7.jar:3.11.7]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:718) ~[apache-cassandra-3.11.7.jar:3.11.7]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652) ~[apache-cassandra-3.11.7.jar:3.11.7]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397) [apache-cassandra-3.11.7.jar:3.11.7]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:631) [apache-cassandra-3.11.7.jar:3.11.7]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:758) [apache-cassandra-3.11.7.jar:3.11.7]
```
